font_family            Fira Code
bold_font              auto
italic_font            auto
bold_italic_font       auto
font_size              9

cursor                 #A1F7EB
shell_integration      disabled
cursor_shape           block
cursor_blink_interval  0.4
cursor_trail           0

linux_display_server wayland
enable_audio_bell no
repaint_delay 10
input_delay 3
sync_to_monitor yes


background #1a1b26
foreground #c0caf5

selection_background #33467c
selection_foreground #c0caf5

cursor #c0caf5
# cores basei
color0  #15161e
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #7aa2f7
color5  #bb9af7
color6  #7dcfff
color7  #a9b1d6

# cores brilhantes
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #7aa2f7
color13 #bb9af7
color14 #7dcfff
color15 #c0caf5
