format ="""\\[$username@$hostname\\] \\[$directory\\]\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status
$character"""


right_format = """$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$html"""





[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)[$hostname](bold red)'
disabled = false



[username]
format      = "[$user]($style)"
style_root  = "red bold"
style_user  = "green bold"
show_always = true
disabled    = false

[git_branch]
format = '\([$symbol$branch]($style)\)'


[character]
success_symbol = '[❭](bold green)'

