#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI 

bspc config border_width         2
bspc config window_gap          12

bspc config focus_follows_pointer true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

xsetroot -cursor_name left_ptr &
picom                          &
~/.fehbg                       &
~/.config/polybar/launch.sh    &
